spring:
  application:
    name:  zuul-server
server:
  port: 10002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
zuul:
  sensitiveHeaders: ''
  routes:
    user:
      path: /api/user/**
      stripPrefix: false
      serviceId: user-server
    group:
      path: /api/group/**
      stripPrefix: false
      serviceId: user-server
    edit:
      path: /api/edit/**
      stripPrefix: false
      serviceId: edit-server
