eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 1201
spring:
    application:
        name: config-server
    profiles:
      active: jdbc
    cloud:
        config:
            server:
                jdbc:
                    sql: SELECT _key, _value from config_properties where application=? and profile=?   and label=?
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/cloud_edit?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
        username: root
